# Generated by Django 4.0.4 on 2022-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дисконт'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, null=True, verbose_name='Новинка'),
        ),
    ]
