# Generated by Django 4.0.4 on 2022-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_is_discount_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/categories', verbose_name='Фото'),
        ),
    ]
